apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment3
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
      - name: ecr-key
      containers:
      - name: myapp
        image: 643572392930.dkr.ecr.eu-west-1.amazonaws.com/sast:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
