apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment3
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
      - name: ecr-key
      containers:
      - name: myapp
        image: 590183770136.dkr.ecr.ap-south-1.amazonaws.com/myapptechstart:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
